services:
  # 後端服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prompt-master-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - backend_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  # 前端服務
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    container_name: prompt-master-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Redis 服務
  redis:
    image: redis:7-alpine
    container_name: prompt-master-redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - app-network

volumes:
  backend_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
