/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TemplatesIndexRouteImport } from "./routes/templates/index";
import { Route as PromptIndexRouteImport } from "./routes/prompt/index";
import { Route as HistoryIndexRouteImport } from "./routes/history/index";

// Create/Update Routes

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: "/templates/",
  path: "/templates/",
  getParentRoute: () => rootRoute,
} as any);

const PromptIndexRoute = PromptIndexRouteImport.update({
  id: "/prompt/",
  path: "/prompt/",
  getParentRoute: () => rootRoute,
} as any);

const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: "/history/",
  path: "/history/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/history/": {
      id: "/history/";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof HistoryIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/prompt/": {
      id: "/prompt/";
      path: "/prompt";
      fullPath: "/prompt";
      preLoaderRoute: typeof PromptIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/templates/": {
      id: "/templates/";
      path: "/templates";
      fullPath: "/templates";
      preLoaderRoute: typeof TemplatesIndexRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Add type-safety to the createFileRoute function across the route tree

declare module "./routes/index" {
  const createFileRoute: CreateFileRoute<
    "/",
    FileRoutesByPath["/"]["parentRoute"],
    FileRoutesByPath["/"]["id"],
    FileRoutesByPath["/"]["path"],
    FileRoutesByPath["/"]["fullPath"]
  >;
}
declare module "./routes/history/index" {
  const createFileRoute: CreateFileRoute<
    "/history/",
    FileRoutesByPath["/history/"]["parentRoute"],
    FileRoutesByPath["/history/"]["id"],
    FileRoutesByPath["/history/"]["path"],
    FileRoutesByPath["/history/"]["fullPath"]
  >;
}
declare module "./routes/prompt/index" {
  const createFileRoute: CreateFileRoute<
    "/prompt/",
    FileRoutesByPath["/prompt/"]["parentRoute"],
    FileRoutesByPath["/prompt/"]["id"],
    FileRoutesByPath["/prompt/"]["path"],
    FileRoutesByPath["/prompt/"]["fullPath"]
  >;
}
declare module "./routes/templates/index" {
  const createFileRoute: CreateFileRoute<
    "/templates/",
    FileRoutesByPath["/templates/"]["parentRoute"],
    FileRoutesByPath["/templates/"]["id"],
    FileRoutesByPath["/templates/"]["path"],
    FileRoutesByPath["/templates/"]["fullPath"]
  >;
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/history": typeof HistoryIndexRoute;
  "/prompt": typeof PromptIndexRoute;
  "/templates": typeof TemplatesIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/history": typeof HistoryIndexRoute;
  "/prompt": typeof PromptIndexRoute;
  "/templates": typeof TemplatesIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/history/": typeof HistoryIndexRoute;
  "/prompt/": typeof PromptIndexRoute;
  "/templates/": typeof TemplatesIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/history" | "/prompt" | "/templates";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/history" | "/prompt" | "/templates";
  id: "__root__" | "/" | "/history/" | "/prompt/" | "/templates/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  HistoryIndexRoute: typeof HistoryIndexRoute;
  PromptIndexRoute: typeof PromptIndexRoute;
  TemplatesIndexRoute: typeof TemplatesIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  PromptIndexRoute: PromptIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/history/",
        "/prompt/",
        "/templates/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    },
    "/prompt/": {
      "filePath": "prompt/index.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
